### ISSUE TITLE
Functions of web

### ISSUE THREAD

**Issue by windoes** [php-fusion/locales#49]
**Describe the bug**
Downloads not working, as it doesn't download when you press on them, also doesnt show any description you put. 
Shoutbox doesn't post messages
Comments not working properly. also on custom pages you cannot comment at all, just show that no comments are writen.
Loads of other technical issues I'm having by trying to use Lithuanian language on this php-fusion version. Seems like I will have to drop the website and create new one with english language, which would make difficult for people that im expecting into the website.

**Version**
PHP-Fusion version. newest.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by RobiNN1** [comment]
This repo is for locales.

And I need the exact version `PHP-Fusion version. newest.`

**Comment by windoes** [comment]
9.03.80.

**Comment by windoes** [comment]
Found out it was design fault for the downloads.

**Comment by RobiNN1** [comment]
This repo is for translations only. Use our forum https://www.php-fusion.co.uk/
